# Generated by Django 5.2 on 2025-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_info_MODEL',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=100, unique=True)),
                ('teacher_phone', models.CharField(max_length=15, unique=True)),
                ('teacher_address', models.TextField()),
                ('teacher_subject', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Teacher Information',
                'verbose_name_plural': 'Teachers Information',
                'db_table': 'teacher_info',
            },
        ),
    ]
