# Generated by Django 5.2 on 2025-07-20 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Info_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info_MODEL',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=20)),
                ('Student_phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Phone number must be 11 digits.')])),
                ('Student_email', models.EmailField(max_length=30, unique=True)),
                ('Student_address', models.TextField()),
                ('Section', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Students Information',
                'db_table': 'student_info',
            },
        ),
        migrations.AlterField(
            model_name='teacher_info_model',
            name='teacher_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_info_model',
            name='teacher_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_info_model',
            name='teacher_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Phone number must be 11 digits.')]),
        ),
        migrations.AlterField(
            model_name='teacher_info_model',
            name='teacher_subject',
            field=models.CharField(max_length=20),
        ),
    ]
